# Generated by Django 5.1.7 on 2025-10-08 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GameMode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mode", models.CharField(max_length=50)),
                ("attempt", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "iq",
                    models.FloatField(
                        blank=True, help_text="Overall IQ for this attempt", null=True
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "date", "attempt")},
            },
        ),
        migrations.CreateModel(
            name="GameQuestionRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_number", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "time",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Time in seconds for this question",
                        null=True,
                    ),
                ),
                ("streak", models.PositiveIntegerField(default=0)),
                ("user_answer", models.CharField(blank=True, max_length=255)),
                ("correct_answer", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("correct", "Correct"),
                            ("incorrect", "Incorrect"),
                            ("skipped", "Skipped"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "game_mode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="MathCraft_Game.gamemode",
                    ),
                ),
            ],
            options={
                "ordering": ["question_number"],
                "unique_together": {("game_mode", "question_number")},
            },
        ),
    ]
